name: jekyll_app
type: ruby:2.5
disk: 1024
web:
  locations:
    "/":
      root: "_site"
      index:
        - index.html
      passthru: false
hooks:
  build: |
    gem install bundler
    bundle install
    JEKYLL_ENV=production bundle exec jekyll build
  post_deploy: |
    if [ "$PLATFORM_BRANCH" = master ]; then
    bundle exec jekyll algolia
    fi
