name: jekyll_app
type: ruby:2.7
disk: 1024
web:
  locations:
    "/":
      root: "_site"
      index:
        - index.html
      passthru: false
      headers:
        Content-Security-Policy: upgrade-insecure-requests
        X-Content-Type-Options: nosniff
        X-Frame-Options: SAMEORIGIN
        X-XSS-Protection: 1; mode=block
hooks:
  build: |
    gem install bundler
    bundle install
    JEKYLL_ENV=production bundle exec jekyll build
  post_deploy: |
    if [ "$PLATFORM_BRANCH" = master ]; then
    bundle exec jekyll algolia
    fi
