---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url:
sections:
- type: jekyll-pages
  label: Pages
  create: all
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"