# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# eventsfor the master and Staging branch
on:
  pull_request:
    branches: [ master, Staging ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Verify:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3
    # Set up ruby which we use in the verify shell script
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'

    # Runs a single command using the runners shell
    - name: install node modules
      run: npm install
    - name: Verify
      run: npm run verify